N: 1024
Nsub: 512
SNRin: [0, 10, 20, 30]
repetitions: 50
parallelize: True
verbosity: 4  
using_signals: ['LinearChirp','CosChirp',           # Single-component signals
                #'ToneSharpAttack', ToneDumped,                  # Dumped and Sharps attacks
                #'McCrossingChirps',                             # Crossing-components  
                'McMultiLinear', 'McCosPlusTone',               # Multi-Component signals  
                'McMultiCos2',                                  # Multi-Component Non-Harmonic  
                #'McSyntheticMixture2',
                #'HermiteFunction',                              # Hermite type signals  
                'McTripleImpulse',]
                #'McOnOffTones','McOnOff2']                      # Modes that born and die
