N: 512
# Nsub: None
SNRin: [0, 10, 20, 30]
repetitions: 5
parallelize: False
verbosity: 4  
using_signals: ['LinearChirp','CosChirp',]           # Single-component signals
                #'ToneSharpAttack', ToneDumped,                  # Dumped and Sharps attacks
                #'McCrossingChirps',                             # Crossing-components  
                # 'McMultiLinear', 'McCosPlusTone',               # Multi-Component signals  
                # 'McMultiCos2',                                  # Multi-Component Non-Harmonic  
                #'McSyntheticMixture2',
                #'HermiteFunction',                              # Hermite type signals  
                # 'McTripleImpulse',]
                #'McOnOffTones','McOnOff2']                      # Modes that born and die
                
# Run again the same benchmark but with new methods:
add_new_methods: True