N: 512
Nsub: 256
SNRin: [0, 10] #, 20, 30]
repetitions: 5
parallelize: False
using_signals: ['LinearChirp',] #'CosChirp', 'ExpChirp',]             # Single-component signals
                # 'ToneSharpAttack', ToneDumped,                  # Dumped and Sharps attacks
                # 'McCrossingChirps',                 # Crossing-components  
                # 'McMultiLinear', 'McCosPlusTone',   # Multi-Component signals  
                # 'McMultiCos2',     # Multi-Component Non-Harmonic  
                # 'McSyntheticMixture2',
                # 'HermiteFunction',                  # Hermite type signals  
                # 'McTripleImpulse',
                # 'McOnOffTones','McOnOff2']                   # Modes that born and die
verbosity: 4  