N: 512
SNRin: [0, 10, 20, 30]
repetitions: 30
parallelize: 5
using_signals: ['CosChirp', 'ExpChirp',             # Single-component signals
                'ToneSharpAttack',                  # Dumped and Sharps attacks
                'McCrossingChirps',                 # Crossing-components  
                'McMultiLinear', 'McCosPlusTone',   # Multi-Component signals  
                'McMultiCos',     # Multi-Component Non-Harmonic  
                'McSyntheticMixture2','McSyntheticMixture3',
                'HermiteFunction',                  # Hermite type signals  
                'McImpulses','McTripleImpulse']
                # 'McOnOffTones']                   # Modes that born and die
verbosity: 4  