N: 1024
# Nsub: None
SNRin: [-5, 0, 10, 20]
repetitions: 100
parallelize: False
verbosity: 5 
signal_ids: [   
                'McMultiLinear', 
                'McMultiLinear2',                       # Multi-Component signals  
                'McSyntheticMixture',
                'McSyntheticMixture2',
                'McSyntheticMixture3',
                'McSyntheticMixture4',
                'HermiteFunction',                              # Hermite type signals  
              ]


# Run again the same benchmark but with new methods:
add_new_methods: False
