[tool.poetry]
name = "benchmark-demo"
version = "0.1.0"
description = "A benchmark for testing tf methods."
authors = ["J. M. Miramont"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = "^1.22.0"
matplotlib = "^3.5.1"
pandas = "^1.3.5"
scipy = "^1.7.3"
ipykernel = "^6.6.1"
seaborn = "^0.11.2"
cmocean = "^2.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
